<?php

namespace Clases;

use Clases\Type;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;

class Pub_gestdocenteClassmap
{
    public static function getCollection() : \Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('ArrayOfClaseAgrupaciones', Type\ArrayOfClaseAgrupaciones::class),
            new ClassMap('ClaseAgrupaciones', Type\ClaseAgrupaciones::class),
            new ClassMap('ArrayOfClaseFechaExamenesAsi', Type\ArrayOfClaseFechaExamenesAsi::class),
            new ClassMap('ClaseFechaExamenesAsi', Type\ClaseFechaExamenesAsi::class),
            new ClassMap('ArrayOfClaseFechaExamenesAsiTotal', Type\ArrayOfClaseFechaExamenesAsiTotal::class),
            new ClassMap('ClaseFechaExamenesAsiTotal', Type\ClaseFechaExamenesAsiTotal::class),
            new ClassMap('ArrayOfClaseFechaExamenesAsiNue', Type\ArrayOfClaseFechaExamenesAsiNue::class),
            new ClassMap('ClaseFechaExamenesAsiNue', Type\ClaseFechaExamenesAsiNue::class),
            new ClassMap('ArrayOfClaseFechaExamenesPlan', Type\ArrayOfClaseFechaExamenesPlan::class),
            new ClassMap('ClaseFechaExamenesPlan', Type\ClaseFechaExamenesPlan::class),
            new ClassMap('ArrayOfClaseAsiDepto', Type\ArrayOfClaseAsiDepto::class),
            new ClassMap('ClaseAsiDepto', Type\ClaseAsiDepto::class),
            new ClassMap('ArrayOfClaseDatosAsig', Type\ArrayOfClaseDatosAsig::class),
            new ClassMap('ClaseDatosAsig', Type\ClaseDatosAsig::class),
            new ClassMap('ArrayOfClaseHorarioAgrp', Type\ArrayOfClaseHorarioAgrp::class),
            new ClassMap('ClaseHorarioAgrp', Type\ClaseHorarioAgrp::class),
            new ClassMap('ArrayOfClaseHorarios', Type\ArrayOfClaseHorarios::class),
            new ClassMap('ClaseHorarios', Type\ClaseHorarios::class),
            new ClassMap('ArrayOfClaseTitulosUni', Type\ArrayOfClaseTitulosUni::class),
            new ClassMap('ClaseTitulosUni', Type\ClaseTitulosUni::class),
            new ClassMap('ArrayOfClaseDatosPlan', Type\ArrayOfClaseDatosPlan::class),
            new ClassMap('ClaseDatosPlan', Type\ClaseDatosPlan::class),
            new ClassMap('ArrayOfClasePlanesAsig', Type\ArrayOfClasePlanesAsig::class),
            new ClassMap('ClasePlanesAsig', Type\ClasePlanesAsig::class),
            new ClassMap('ArrayOfClasePlanesDep', Type\ArrayOfClasePlanesDep::class),
            new ClassMap('ClasePlanesDep', Type\ClasePlanesDep::class),
            new ClassMap('ArrayOfClaseDptoAsig', Type\ArrayOfClaseDptoAsig::class),
            new ClassMap('ClaseDptoAsig', Type\ClaseDptoAsig::class),
            new ClassMap('ArrayOfClaseAreasDpto', Type\ArrayOfClaseAreasDpto::class),
            new ClassMap('ClaseAreasDpto', Type\ClaseAreasDpto::class),
            new ClassMap('ArrayOfClaseDptoCen', Type\ArrayOfClaseDptoCen::class),
            new ClassMap('ClaseDptoCen', Type\ClaseDptoCen::class),
            new ClassMap('ArrayOfClaseAsiPlan', Type\ArrayOfClaseAsiPlan::class),
            new ClassMap('ClaseAsiPlan', Type\ClaseAsiPlan::class),
            new ClassMap('ArrayOfClaseCalificaciones', Type\ArrayOfClaseCalificaciones::class),
            new ClassMap('ClaseCalificaciones', Type\ClaseCalificaciones::class),
            new ClassMap('ArrayOfClaseConvocatorias', Type\ArrayOfClaseConvocatorias::class),
            new ClassMap('ClaseConvocatorias', Type\ClaseConvocatorias::class),
            new ClassMap('ArrayOfClaseGrupoAsi', Type\ArrayOfClaseGrupoAsi::class),
            new ClassMap('ClaseGrupoAsi', Type\ClaseGrupoAsi::class),
            new ClassMap('ArrayOfClaseConveMovilidad', Type\ArrayOfClaseConveMovilidad::class),
            new ClassMap('ClaseConveMovilidad', Type\ClaseConveMovilidad::class),
            new ClassMap('ArrayOfClaseTitulosPropiosUni', Type\ArrayOfClaseTitulosPropiosUni::class),
            new ClassMap('ClaseTitulosPropiosUni', Type\ClaseTitulosPropiosUni::class),
            new ClassMap('ClaseReqidiomab1plan', Type\ClaseReqidiomab1plan::class),
            new ClassMap('wsagrupaciones', Type\Wsagrupaciones::class),
            new ClassMap('wsagrupacionesResponse', Type\WsagrupacionesResponse::class),
            new ClassMap('wsfechaexamenesasi', Type\Wsfechaexamenesasi::class),
            new ClassMap('wsfechaexamenesasiResponse', Type\WsfechaexamenesasiResponse::class),
            new ClassMap('wsfechaexamenesasitotal', Type\Wsfechaexamenesasitotal::class),
            new ClassMap('wsfechaexamenesasitotalResponse', Type\WsfechaexamenesasitotalResponse::class),
            new ClassMap('wsfechaexamenesasinue', Type\Wsfechaexamenesasinue::class),
            new ClassMap('wsfechaexamenesasinueResponse', Type\WsfechaexamenesasinueResponse::class),
            new ClassMap('wsfechaexamenesplan', Type\Wsfechaexamenesplan::class),
            new ClassMap('wsfechaexamenesplanResponse', Type\WsfechaexamenesplanResponse::class),
            new ClassMap('wsasidepto', Type\Wsasidepto::class),
            new ClassMap('wsasideptoResponse', Type\WsasideptoResponse::class),
            new ClassMap('wsdatosasig', Type\Wsdatosasig::class),
            new ClassMap('wsdatosasigResponse', Type\WsdatosasigResponse::class),
            new ClassMap('wshorarioagrp', Type\Wshorarioagrp::class),
            new ClassMap('wshorarioagrpResponse', Type\WshorarioagrpResponse::class),
            new ClassMap('wshorarios', Type\Wshorarios::class),
            new ClassMap('wshorariosResponse', Type\WshorariosResponse::class),
            new ClassMap('wstitulosuni', Type\Wstitulosuni::class),
            new ClassMap('wstitulosuniResponse', Type\WstitulosuniResponse::class),
            new ClassMap('wsdatosplan', Type\Wsdatosplan::class),
            new ClassMap('wsdatosplanResponse', Type\WsdatosplanResponse::class),
            new ClassMap('wsplanesasig', Type\Wsplanesasig::class),
            new ClassMap('wsplanesasigResponse', Type\WsplanesasigResponse::class),
            new ClassMap('wsplanesdep', Type\Wsplanesdep::class),
            new ClassMap('wsplanesdepResponse', Type\WsplanesdepResponse::class),
            new ClassMap('wsdptoasig', Type\Wsdptoasig::class),
            new ClassMap('wsdptoasigResponse', Type\WsdptoasigResponse::class),
            new ClassMap('wsareasdpto', Type\Wsareasdpto::class),
            new ClassMap('wsareasdptoResponse', Type\WsareasdptoResponse::class),
            new ClassMap('wsdptocen', Type\Wsdptocen::class),
            new ClassMap('wsdptocenResponse', Type\WsdptocenResponse::class),
            new ClassMap('wsasiplan', Type\Wsasiplan::class),
            new ClassMap('wsasiplanResponse', Type\WsasiplanResponse::class),
            new ClassMap('wscalificaciones', Type\Wscalificaciones::class),
            new ClassMap('wscalificacionesResponse', Type\WscalificacionesResponse::class),
            new ClassMap('wsconvocatorias', Type\Wsconvocatorias::class),
            new ClassMap('wsconvocatoriasResponse', Type\WsconvocatoriasResponse::class),
            new ClassMap('wsgruposasi', Type\Wsgruposasi::class),
            new ClassMap('wsgruposasiResponse', Type\WsgruposasiResponse::class),
            new ClassMap('wsconvemovilidad', Type\Wsconvemovilidad::class),
            new ClassMap('wsconvemovilidadResponse', Type\WsconvemovilidadResponse::class),
            new ClassMap('wstitulospropiosuni', Type\Wstitulospropiosuni::class),
            new ClassMap('wstitulospropiosuniResponse', Type\WstitulospropiosuniResponse::class),
            new ClassMap('wsreqidiomab1plan', Type\Wsreqidiomab1plan::class),
            new ClassMap('wsreqidiomab1planResponse', Type\Wsreqidiomab1planResponse::class),
        );
    }
}

